In [ ]:
### import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)


###  Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
###      to print the data types of both the variables.


In [11]:
#Ans - data type of list_ is list whereas data type of array_ is array.
#numpy arrays are faster and store small size as compared to lists.
## list variable
try:
    ls=[x for x in range(1000000)]
    type(ls)
except Exception as e:
    print(e)

### array variable 
try:
    import numpy as np
    arr=np.array([x for x in range(1000000)])
    type(arr)
except Exception as e:
    print(e)

list

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [19]:
## printing each element of each LIST 
list_ = [ '1' , '2' , '3' , '4' , '5' ]
for i in list_:
    print(f"data type of {i} is", type(i))
    
## printing each element of each ARRAY
print()
import numpy as np
array_list = np.array(object = list_)
print(len(array_list))
for i in range(len(array_list)):
    print(f"data type of {array_list[i]} is",type(array_list[i]))
    

data type of 1 is <class 'str'>
data type of 2 is <class 'str'>
data type of 3 is <class 'str'>
data type of 4 is <class 'str'>
data type of 5 is <class 'str'>

5
data type of 1 is <class 'numpy.str_'>
data type of 2 is <class 'numpy.str_'>
data type of 3 is <class 'numpy.str_'>
data type of 4 is <class 'numpy.str_'>
data type of 5 is <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and 
### arra_list? If so then print the data types of each and every element present in both the variables, list_ 
### and arra_list.

In [22]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)
for i in list_:
    print(f"data type of {i} is", type(i))
print(array_list)
## there will NOT be any change in elemets present in list_ variable
## For arrays there is a change in data type of elements , now its int instead of string
for i in range(len(array_list)):
    print(f"data type of {array_list[i]} is",type(array_list[i]))

data type of 1 is <class 'str'>
data type of 2 is <class 'str'>
data type of 3 is <class 'str'>
data type of 4 is <class 'str'>
data type of 5 is <class 'str'>
[1 2 3 4 5]
data type of 1 is <class 'numpy.int64'>
data type of 2 is <class 'numpy.int64'>
data type of 3 is <class 'numpy.int64'>
data type of 4 is <class 'numpy.int64'>
data type of 5 is <class 'numpy.int64'>


## import numpy as np
## num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
## num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i)	 shape
### (ii) size

In [26]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array)
print(num_array.shape)   ## shape is number of rows, number of columns so here its 2,3 as 2 rows , 3 columns
print()
print(num_array.size)    ## size attribute of numpy array gives size , for single dimensional array len() can also be usedd

[[1 2 3]
 [4 5 6]]
(2, 3)

6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
### creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]



In [36]:
## there are multiple methos to do this, two are here below
## a) creating a 3,3 multi dimensional array ith all zeros
import numpy as npm
arrzmd=np.zeros((3,3))  
print(arrzmd)
print(arrzmd.shape)   ## shape is 3,3
print(arrzmd.size)    ## size is 9
print()
print()
## b) creating a single dimensional array of 9 zeros with all zeros & then reshape it
arrsd=np.array([0]*9)
print(arrsd)
newarr=arrsd.reshape(3,3)
print(newarr)
print(newarr.shape)   ## shape is 3,3
print(newarr.size)    ## size is 9


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


[0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
9


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [39]:
import numpy as np
x=np.eye(5,5)  ## 3 rows , each with 5 columns.
print(x) 
print()
print(x.shape) 
print()
print(x.size) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

(5, 5)

25
